spring:
  application:
    name: ticketrush

  datasource:
    url: jdbc:postgresql://localhost:5433/ticketrush?options=-c%20TimeZone%3DUTC
    username: ticketrush
    password: ticketrush_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
